### ISSUE TITLE
Question regarding the usage of KisiBeaconTracker

### ISSUE THREAD

**Issue by danieltrotter** [kisi-inc/kisi-android-st2u-sdk-public#2]
Hello, I am integrating Kisi SDK into flutter project, but I am unable to import `KisiBeaconTracker` even after I upgrade aar file into `kisi-st2a-0.4.aar`
Do I miss anything?
Thanks in advance

**Comment by danieltrotter** [comment]
When I run `beaconTracker.startRanging()` suddenly the app crashes
Crash log has attached below
```
java.lang.NoClassDefFoundError: Failed resolution of: Laga/android/luch/BeaconScanner$Builder;
        at de.kisi.android.nearby.KisiBeaconTracker$luchScanner$2.invoke(KisiBeaconTracker.kt:49)
        at de.kisi.android.nearby.KisiBeaconTracker$luchScanner$2.invoke(KisiBeaconTracker.kt:48)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at de.kisi.android.nearby.KisiBeaconTracker.getLuchScanner(KisiBeaconTracker.kt:48)
        at de.kisi.android.nearby.KisiBeaconTracker.startRanging(KisiBeaconTracker.kt:69)
        at com.example.flutter_kisi.KisiActivity.onResume(KisiActivity.kt:29)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7415)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "aga.android.luch.BeaconScanner$Builder" on path: DexPathList[[zip file "/data/app/com.example.flutter_kisi-U4qjK18IM5cg5FS83_xVTg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_kisi-U4qjK18IM5cg5FS83_xVTg==/lib/arm64, /data/app/com.example.flutter_kisi-U4qjK18IM5cg5FS83_xVTg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

I also tried to catch the crash error, but no luck
I am attaching piece of code too

```
package com.example.flutter_kisi

import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import de.kisi.android.nearby.KisiBeaconTracker

class KisiActivity : AppCompatActivity() {
    lateinit var beaconTracker: KisiBeaconTracker


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_kisi)
        beaconTracker = KisiBeaconTracker(
            this,
            onScanFailure = { e ->
                // Here you can get notifications about beacon scan failures
            },
            onBeaconsDetected = { beacons ->
                // TODO handle beacons
            }
        )
    }

    override fun onResume() {
        super.onResume()
        try {
            beaconTracker.startRanging()
            Toast.makeText(
                this, "onResume",
                Toast.LENGTH_LONG
            ).show()
        } catch (e : Exception) {
            Toast.makeText(
                this, e.toString(),
                Toast.LENGTH_LONG
            ).show()
        }
    }

    override fun onPause() {
        super.onPause()
        try {
            beaconTracker.stopRanging()
            Toast.makeText(
                this, "onPause",
                Toast.LENGTH_LONG
            ).show()
        } catch (e : Exception) {
            Toast.makeText(
                this, e.toString(),
                Toast.LENGTH_LONG
            ).show()
        }
    }
}
```
It will be highly appriciated if you could upload sample project for usage of `KisiBeaconTracker`

Thanks in advance

**Comment by agap** [comment]
Hi, Daniel,

There is one more dependency that you will have to add to your app module's `build.gradle` file to make it work:

```gradle
implementation 'aga.android:luch:0.3.1'
```

This is available through jcenter so you'll have to add it to the `build.gradle` file in the project root like so:

```gradle
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() // <-- add this line
    }
}
```

**Comment by ce07c3** [comment]
I am assuming that solved it - else please reopen. 🙂
