### ISSUE TITLE
Crash after door unlock

### ISSUE THREAD

**Issue by pnogier** [kisi-inc/kisi-android-st2u-sdk-public#7]
Hi there,

We are implementing the SDK on React Native, we managed to get it working properly for the iOS SDK, but having issues now with the Android SDK. 

We are very close of getting this working 100%, basically everything works like a charm, init the SDK, opening the door by tapping the device against the reader, but then, directly after the door opens, the app crashes.

Here is the stack we get: 
```shell
Binding to service ComponentInfo{com.getspacial.mobileapp/com.getspacial.mobileapp.SecureUnlockService}
 E  FATAL EXCEPTION: main
Process: com.getspacial.mobileapp, PID: 10996
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH at [com.android.org](http://com.android.org/).conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
at [com.android.org](http://com.android.org/).conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
at [com.android.org](http://com.android.org/).conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:365)
at javax.crypto.Cipher.doFinal(Cipher.java:2055)
at de.kisi.android.st2u.requests.SecureChannelCommunicationHandler.decrypt(SecureChannelCommunicationHandler.kt:123)
at de.kisi.android.st2u.requests.SecureChannelCommunicationHandler.handle(SecureChannelCommunicationHandler.kt:54)
at de.kisi.android.st2u.SecureUnlock.handle(SecureUnlock.kt:84)
at com.getspacial.mobileapp.SecureUnlockService.processCommandApdu(SecureUnlockService.java:57)
at android.nfc.cardemulation.HostApduService$MsgHandler.handleMessage(HostApduService.java:263)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Did anyone encounter the same issue ? 

It obviously might be something that we are missing. 

Thanks in advance for looking into this issue.

**Comment by agap** [comment]
Hi!

Could you please show how the `SecureUnlockService` gets started? Are you trying to e.g. start it yourself, or you leave it up to the OS to be started at an appropriate moment?

**Comment by pnogier** [comment]
Hi @agap ,

Sure, gonna show you my implementation which is really basic.

### `SecureUnlockManager.java`
```java
import de.kisi.android.st2u.SecureUnlock;

public class SecureUnlockManager {
    private static SecureUnlock secureUnlockInstance;

    private SecureUnlockManager() {}

    public static synchronized void initialize(SecureUnlock secureUnlock) {
        secureUnlockInstance = secureUnlock;
    }

    public static synchronized SecureUnlock getInstance() {
        return secureUnlockInstance;
    }
}
```

### `KisiModule.java`
```java
import android.content.Context;
import android.util.Log;

import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.WritableMap;

import io.reactivex.rxjava3.core.Maybe;
import de.kisi.android.st2u.Login;
import de.kisi.android.st2u.SecureUnlock;
import de.kisi.android.st2u.UnlockError;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;

public class KisiModule extends ReactContextBaseJavaModule {

    private static ReactApplicationContext reactContext;

    public KisiModule(ReactApplicationContext context) {
        super(context);
        reactContext = context;
    }

    @Override
    public String getName() {
        return "KisiModule";
    }

    @ReactMethod
    public void initialize(String accessToken, ReadableMap kisiLoginObject, Promise promise) {
        try {
            int id = kisiLoginObject.getInt("id");
            String token = kisiLoginObject.getString("token");
            String key = kisiLoginObject.getString("key");
            String certificate = kisiLoginObject.getString("certificate");

            SecureUnlock secureUnlock = SecureUnlock.Companion.with(
                    OUR_SDK_KEY,
                    true,
                    reactContext,
                    organizationId -> Maybe.just(
                            new Login(
                                    id,
                                    token,
                                    key,
                                    certificate
                            )
                    ),
                    new Function1<UnlockError, Unit>() {
                        @Override
                        public Unit invoke(UnlockError unlockError) {
                            Log.d("SecureUnlock", "Unlock error callback invoked");
                            return Unit.INSTANCE;
                        }
                    }
            );

            SecureUnlockManager.initialize(secureUnlock);

            WritableMap resultMap = Arguments.createMap();
            resultMap.putInt("id", id);
            resultMap.putString("token", token);
            resultMap.putString("key", key);
            resultMap.putString("certificate", certificate);

            promise.resolve(resultMap);
        } catch (Exception e) {
            promise.reject("Initialization error", e);
        }
    }
}
```

### `SecureUnlockService.java`
```java
import android.nfc.cardemulation.HostApduService;
import android.os.Bundle;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.modules.core.DeviceEventManagerModule;
import io.reactivex.rxjava3.disposables.Disposable;
import io.reactivex.rxjava3.observers.DisposableSingleObserver;
import de.kisi.android.st2u.SecureUnlock;

public class SecureUnlockService extends HostApduService {

    private SecureUnlock secureUnlock;
    private Disposable disposable;
    private static ReactApplicationContext reactContext;

    public SecureUnlockService() {
        super();
    }

    public SecureUnlockService(ReactApplicationContext context) {
        super();
        reactContext = context;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        sendEvent("onCreate", "Service created");

        secureUnlock = SecureUnlockManager.getInstance();

        if (secureUnlock != null) {
            sendEvent("initialize", "Init: SecureUnlock initialized");
        } else {
            sendEvent("initialize", "Init: SecureUnlock is not initialized");
        }
    }

    @Override
    public byte[] processCommandApdu(byte[] commandApdu, Bundle extras) {
        secureUnlock = SecureUnlockManager.getInstance();
        if (secureUnlock == null) {
            return null;
        }

        disposable = secureUnlock
                .handle(commandApdu)
                .subscribeWith(new DisposableSingleObserver<byte[]>() {
                    @Override
                    public void onSuccess(byte[] t) {
                        sendResponseApdu(t);
                    }

                    @Override
                    public void onError(Throwable e) {
                        sendEvent("processCommandApduError", "Error processing command APDU: " + e.getMessage());
                        sendResponseApdu(null);
                    }
                });

        return null;
    }

    @Override
    public void onDeactivated(int reason) {
        String reasonString = "Unknown";
        switch (reason) {
            case DEACTIVATION_LINK_LOSS:
                reasonString = "DEACTIVATION_LINK_LOSS";
                break;
            case DEACTIVATION_DESELECTED:
                reasonString = "DEACTIVATION_DESELECTED";
                break;
        }
        sendEvent("onDeactivated", "Service deactivated with reason: " + reasonString);
        if (disposable != null && !disposable.isDisposed()) {
            disposable.dispose();
        }
        disposable = null;
    }

    private void sendEvent(String eventName, String eventData) {
        if (reactContext != null) {
            reactContext
                    .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit(eventName, eventData);
        }
    }
}
```


So basically the SDK is initialized from the React Native NativeModule using the `KisiModule` class `initialize` method. 
Then the instance is saved into the `SecureUnlockManager`

And here is how the `SecureUnlockService` is defined in my `AndroidManifest.xml`:
```xml
        <service
            android:name=".SecureUnlockService"
            android:exported="true"
            android:permission="android.permission.BIND_NFC_SERVICE">
            <intent-filter>
                <action android:name="android.nfc.cardemulation.action.HOST_APDU_SERVICE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <meta-data
                android:name="android.nfc.cardemulation.host_apdu_service"
                android:resource="@xml/hce_service" />
        </service>
```

Hope it gives you more information about my integration.
I don't have that much knowledge in Android development as I am just a React/RN developer so I might be missing something important

**Comment by pnogier** [comment]
Hi @agap,

Any chance you've looked into it ?

**Comment by agap** [comment]
@pnogier sorry, I was OOO yesterday, so couldn't respond in time :(

Judging by your code (thanks for posting all the relevant parts, by the way, it really helps in figuring out what's going on!), it seems like you initialize `SecureUnlock` once and then you (re)use it for all communication attempts. 

This is a stateful class, ans its objects are meant to be used created and used once for each communication attempt as it keeps the entire session inside itself. So I'd recommend to initiate it directly in `SecureUnlockService#onCreate` as it's done in the example code.

Most likely your issue will be resolved once you do it, but don't hesitate to ping me if you encounter anything else!

**Comment by pnogier** [comment]
@agap,

You are our hero 🎉 , as you said, the issue has been resolved as soon as I changed the way we initialized the class. 
Thank you so much for your help,

Have a great end of week 🙏

**Comment by ce07c3** [comment]
Great to hear :)

**Comment by agap** [comment]
@pnogier glad to see it helped! Have a great end of the week too :+1:
